### ISSUE TITLE
Resolve a few issues with json encoding/decoding

### ISSUE THREAD

**Issue by jeffdeville** [ryanwinchester/hubspotex#8]
I've bumped into 2 issues here:

1. Changing Poison.Encoder.encode("") to Poison.encode!, as per Poison's current docs.  (I can't remember what made me run into this problem)
2. Empty success responses are possible, but the system chokes trying to decode ""

PR forthcoming

**Comment by ryanwinchester** [comment]
fixed in #9 and #10, thanks :)
